on: push
name: Publish backend updates
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install dependencies
        uses: actions/npm@master
        with:
          args: install
      - name: run tests
        uses: actions/npm@master
        with:
          args: run test
      - name: build docker file
        uses: actions/docker/cli@master
        with:
          args: build -t rocketnow/backend .
      - name: login to dockerhub
        uses: actions/docker/login@master
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: docker push
        uses: actions/docker/cli@master
        with:
          args: push rocketnow/backend
